id = "sync-dark"
name = "Sync Dark"
version = "1.0.0"
schema_version = 0
description = "A dark-minimalistic theme based on Radix Color System for Zed."
repository = "https://github.com/rollsmorr1/sync-zed-theme"
authors = ["Royce Moroch <morochroyce@gmail.com>"]
themes = ["themes/sync-dark.json"]
languages = []

[lib]

[grammars]

[language_servers]
